version: '3.8'
services:

  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - Inception
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    volumes:
      - "wordpress:/var/www/html/wordpress"
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - Inception
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    healthcheck:
      test: ["CMD", "php-fpm83", "-t"]
      interval: 3s
      timeout: 30s
      retries: 3

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - "wordpress:/var/www/html/wordpress"
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - Inception
    restart: always
    env_file:
      - .env

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suibrahi/data/db-data
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suibrahi/data/www-data

networks:
  Inception:
    name: Inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
